"""add blacklist chapters

Revision ID: 05325083c12a
Revises: 31291f4303a0
Create Date: 2025-11-24 15:12:27.984915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '05325083c12a'
down_revision: Union[str, Sequence[str], None] = '31291f4303a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Chapter', 'blacklist_chapters')
    op.add_column('Comic', sa.Column('blacklist_chapters', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Comic', 'blacklist_chapters')
    op.add_column('Chapter', sa.Column('blacklist_chapters', mysql.JSON(), nullable=True))
    # ### end Alembic commands ###
