"""add tags and type

Revision ID: 077dc0c507bf
Revises: 0ef179ec093e
Create Date: 2025-09-30 15:49:21.158311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '077dc0c507bf'
down_revision: Union[str, Sequence[str], None] = '0ef179ec093e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Comic', sa.Column('comic_type', sa.Enum('WEBTOON', 'MANGA', name='comictype'), nullable=False))
    op.add_column('Comic', sa.Column('tags', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Comic', 'tags')
    op.drop_column('Comic', 'comic_type')
    # ### end Alembic commands ###
