"""add scanlation group

Revision ID: 0ef179ec093e
Revises: 
Create Date: 2025-09-26 16:32:42.749536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ef179ec093e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Comic', sa.Column('scanlation_group', sa.Enum('ASURA_SCANS', 'MANGA_FIRE', name='scanlationgroup'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Comic', 'scanlation_group')
    # ### end Alembic commands ###
