"""add update frequency

Revision ID: 156dde3bd66c
Revises: 81cd4d6e399f
Create Date: 2025-11-19 15:46:46.180893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '156dde3bd66c'
down_revision: Union[str, Sequence[str], None] = '81cd4d6e399f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Comic', sa.Column('update_frequency', sa.Enum('WEEKLY', 'BIWEEKLY', 'MONTHLY', name='updatefrequency'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Comic', 'update_frequency')
    # ### end Alembic commands ###
