"""add blacklist chapters

Revision ID: 31291f4303a0
Revises: 156dde3bd66c
Create Date: 2025-11-24 15:10:24.327180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31291f4303a0'
down_revision: Union[str, Sequence[str], None] = '156dde3bd66c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Chapter', sa.Column('blacklist_chapters', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Chapter', 'blacklist_chapters')
    # ### end Alembic commands ###
