"""add user tag link

Revision ID: 857b15584c6f
Revises: 8abe272dfa29
Create Date: 2025-12-02 15:32:50.614288

"""
from typing import Sequence, Union

from alembic import op
import sqlmodel
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '857b15584c6f'
down_revision: Union[str, Sequence[str], None] = '8abe272dfa29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ComicTagLink',
    sa.Column('comic_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['comic_id'], ['Comic.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['Tag.id'], ),
    sa.PrimaryKeyConstraint('comic_id', 'tag_id')
    )
    op.drop_column('Comic', 'tags')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Comic', sa.Column('tags', mysql.JSON(), nullable=True))
    op.drop_table('ComicTagLink')
    op.drop_table('Tag')
    # ### end Alembic commands ###
