"""update user activity

Revision ID: 8abe272dfa29
Revises: faae41c346c0
Create Date: 2025-11-28 18:31:28.243793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8abe272dfa29'
down_revision: Union[str, Sequence[str], None] = 'faae41c346c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('activity_time', sa.Integer(), nullable=False))
    op.add_column('User', sa.Column('last_activity', sa.DateTime(), nullable=False, server_default=sa.func.current_timestamp()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'last_activity')
    op.drop_column('User', 'activity_time')
    # ### end Alembic commands ###
