"""update to current live schema

Revision ID: faae41c346c0
Revises: 05325083c12a
Create Date: 2025-11-28 15:11:30.500438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'faae41c346c0'
down_revision: Union[str, Sequence[str], None] = '05325083c12a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Chapter', 'number',
               existing_type=mysql.FLOAT(),
               type_=sa.Numeric(precision=10, scale=3),
               existing_nullable=False)
    op.add_column('Comic', sa.Column('update_status', sa.Enum('PENDING', 'SUCCESS', 'FAILED', name='updatestatus'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Comic', 'update_status')
    op.alter_column('Chapter', 'number',
               existing_type=sa.Numeric(precision=10, scale=3),
               type_=mysql.FLOAT(),
               existing_nullable=False)
    # ### end Alembic commands ###
