"""changed float to decimal

Revision ID: 0845fdb1b155
Revises: d99379308a6d
Create Date: 2025-11-27 21:54:56.713469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0845fdb1b155'
down_revision: Union[str, Sequence[str], None] = 'd99379308a6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Chapter', 'number',
               existing_type=mysql.FLOAT(),
               type_=sa.Numeric(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Chapter', 'number',
               existing_type=sa.Numeric(),
               type_=mysql.FLOAT(),
               existing_nullable=False)
    # ### end Alembic commands ###
