"""add update status

Revision ID: d99379308a6d
Revises: 
Create Date: 2025-11-26 08:35:43.741059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd99379308a6d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Comic', sa.Column('update_status', sa.Enum('PENDING', 'SUCCESS', 'FAILED', name='updatestatus'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Comic', 'update_status')
    # ### end Alembic commands ###
