"""changed float to decimal

Revision ID: e324c98dc848
Revises: 0845fdb1b155
Create Date: 2025-11-27 22:16:20.806825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e324c98dc848'
down_revision: Union[str, Sequence[str], None] = '0845fdb1b155'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Chapter', 'number',
               existing_type=mysql.DECIMAL(precision=10, scale=0),
               type_=sa.Numeric(precision=10, scale=3),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Chapter', 'number',
               existing_type=sa.Numeric(precision=10, scale=3),
               type_=mysql.DECIMAL(precision=10, scale=0),
               existing_nullable=False)
    # ### end Alembic commands ###
