"""add user tracking data

Revision ID: f900e2ab4731
Revises: e324c98dc848
Create Date: 2025-11-28 19:37:05.094310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f900e2ab4731'
down_revision: Union[str, Sequence[str], None] = 'e324c98dc848'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('activity_time', sa.Integer(), nullable=False))
    op.add_column('User', sa.Column('last_activity', sa.DateTime(), nullable=False, server_default=sa.func.current_timestamp()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'last_activity')
    op.drop_column('User', 'activity_time')
    # ### end Alembic commands ###
