networks:
  manga_network:
    driver: bridge

services:
  mysql:
    image: mysql:8.4.7
    container_name: mysql
    environment:
      - TZ=Europe/Paris
      - MYSQL_ROOT_PASSWORD=pwd
      - MYSQL_DATABASE=manga_reader
    volumes:
      - ./mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 2s
      retries: 10
    restart: always
    networks:
      - manga_network

  reader:
    build:
      context: .
      dockerfile: Dockerfile.reader
    container_name: reader
    environment:
      - TZ=Europe/Paris
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USERNAME=${DB_USERNAME_READER}
      - DB_PASSWORD=${DB_PASSWORD_READER}
      - DB_NAME=manga_reader
      - ENVIRONMENT=${ENVIRONMENT}
      - SECRET_KEY=${SECRET_KEY}
    volumes:
      - ${MOUNTED_STORAGE}:/app/local_comics
    ports:
      - "8888:8888"
    depends_on:
      mysql:
        condition: service_healthy
    restart: always
    networks:
      - manga_network

  scraper:
    build:
      context: .
      dockerfile: Dockerfile.scraper
    container_name: scraper
    environment:
      - TZ=Europe/Paris
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USERNAME=${DB_USERNAME_SCRAPER}
      - DB_PASSWORD=${DB_PASSWORD_SCRAPER}
      - DB_NAME=manga_reader
      - ENVIRONMENT=${ENVIRONMENT}
    volumes:
      - ${MOUNTED_STORAGE}:/app/local_comics
    ports:
      - "8810:8810"
    depends_on:
      mysql:
        condition: service_healthy
    restart: always
    networks:
      - manga_network