scraper:
  user: INFO
  comic: INFO
  chapter: INFO
  page: INFO
  config: INFO
  base-scraper: INFO
  ssl-checker: INFO
  context-manager: DEV
  vrf-generator: INFO
  mangafire: INFO
  asura-scans: INFO
  manga-updater: INFO
  worker-context: INFO
  db-access-layer: INFO
  vrf-telemetry: INFO

reader:
  config: INFO
  user: INFO
  comic: INFO
  chapter: INFO
  page: INFO
  context-manager: DEV
  auth: INFO
  library: INFO
  manga-router: INFO
  chapter-router: DEV
  add-manga: DEV
  base-scraper: INFO
  asura-scans: INFO
  ssl-checker: INFO
  vrf-generator: INFO
  mangafire: INFO
  manga-updater: DEV
  admin: INFO
  app: INFO
  db-access-layer: INFO
  vrf-telemetry: INFO
